name: cdp4common
version: 0.0.1
description: >-
  CDP4 Common Class Library that contains DTOs, PODOs
homepage: https://www.rheagroup.com
repository: https://github.com/RHEAGROUP/CDP4-SDKDart-Community-Edition
issue_tracker: https://github.com/RHEAGROUP/CDP4-SDKDart-Community-Edition/issues

environment:
  sdk: '>=2.0.0 <3.0.0'
  flutter: ^0.1.2